### ISSUE TITLE
Google Cloud Platform issue

### ISSUE THREAD

**Issue by sbrodehl** [cvdfoundation/mnist#2]
Looks like there are some issues with the Google Cloud Platform.

All [links](https://storage.googleapis.com/cvdf-datasets/mnist/train-images-idx3-ubyte.gz) return the following error:

```xml
<Error>
  <Code>UserProjectAccountProblem</Code>
  <Message>User project billing account not in good standing.</Message>
  <Details>
    The billing account for project 81,941,577,218 is disabled in state delinquent
  </Details>
</Error>
```

**Comment by shabbychef** [comment]
what was the solution? asking for a friend.

**Comment by sbrodehl** [comment]
As the error message suggests, it seemed to be an issue related to billing.
The was nothing done on my side to solve this.

**Comment by amanchopra95** [comment]
@sbrodehl can you share how you were able to solve this issue. I am facing the same issue.
